[Features]
;Adjusts the variables used in the Barter formula
;Buy Price = Item Value * (fBarterBuyBase + Barter Skill * fBarterBuyMult / 100)
fBarterBuyBase=2.5
fBarterBuyMult=-1.0
;Sell Price = Item Value * (fBarterSellBase + Barter Skill * fBarterSellMult / 100)
fBarterSellBase=0.15
fBarterSellMult=0.45

;Controls if NCR/Legion money is worthless to non-faction NPCs
bValuelessNCRMoneyToNonNCRVendors=0
bValuelessLegionMoneytoNonLegionVendors=0

;Controls if many common vendors will no longer buy chems
;Only applies if bBarterCheckActorBuySellFlags is enabled in Tweaks
bIllicitChems=1

;Blocks selling to any vendors with the "SEXVendorExclusion" KEYWORD
;In vanilla, this only includes the Lucky 38 Upgrade Terminal and Lonesome Road Commissary Terminal
bNoSellToCertainVendors=1

;Controls cap reward for snow globes
iSnowglobePrice=500

;Controls cap requirement for entry to The Strip
iStripCreditCheck=4000