; ----------------------------- Patching for P6 - Chinese Assault Rifles ------------------------------	\/
P6ChineseAssaultRifle=600
P6ChineseAssaultRifleU1=1200
P6ChineseAssaultRifleU2=2200
ModNVChineseAssaultRifleShortBarrel=150
ModNVChineseAssaultrifleForgedReceiver=200