[SEX]
; ------------------------------------- Patching for Gun and Friends ----------------------------------	\/
; 10mm Pistols
; Price NV: 750
; Price Default: 175
; Price Weathered: 875
WeapNVC6520=200 ; 2200
WeapNVN80=225 ; 800
WeapNV10mmPistolS=225 ; 800
WeapNVEnclavePInf=500 ; 5000
WeapNVAlloyedSteel=225 ; 800
WeapNV10mmTS=220 ; 750
WeapNVC6520Unique=400 ; 400
WeapNVC6520Custom=350 ; 2600
ModNVN80HeavyFrame=125 ; 500
ModWlOmm6520Stub=75 ; 750
ModWlOmm6520Scope=100 ; 100
; 10mm SMGs
; Price NV: 2375
; Price Default: 330
Weap10mmSubmachineGunHandmade=220 ; 800
Weap10mmSubmachineGunClassic=370 ; 3000
Weap10mmSubmachineGunClassUnique=500 ; 4200
Weap10mmSubmachineGunUltra=420 ; 3500
Weap10mmSubmachineGunAlloyed=350 ; 2500
ModWlOmmSMGCAimingM=150 ; 800
ModWlOmmSMGCSight=175 ;800
ModWlOmmSMGHRubber=100 ; 300
; Double Barrel Shotguns
; Price NV: 1950
; Price Default: 100
WeapNVDoubleBarrelshotgun=185 ; 675
WeapNVDoubleBarrelshotgunPaFish=250 ; 900
WeapNVDoubleBarrelshotgunKneecapper=175 ; 1250
WeapShotgunSawedOffMouser=60 ; 50
ModWDoubleBarrelShotgunMapleStock=75 ; 1000
ModWDoubleBarrelShotgunChoke=100 ; 1500
; Hunting Rifles
; Price NV: 2200
; Price Default: 250
WeapXHuntingRifle=85 ; 85
WeapXHuntingRifleUnique=100 ; 100
WeapHuntingRifleRecon=2250 ; 150
; Lever Actions Rifles
; Price NV: 800
; Price Default: 125
WeapNVLeverActionRifle=200 ; 900
WeapNVLeverActionRifleLincolnsRepeater=2000 ; 2000
WeapNVLeverActionRifleBackWater=1500 ; 1500
ModWLARBronzeBody=125 ; 750
ModNVLARNewStock=100 ; 750
ModWLARModernSights=120 ; 750
; Assault Rifles
; Price NV: 3950
; Price Default: 500
WeapAssaultRifleNV=400 ; 2250
WeapAssaultRifleUniqueNV=500 ; 3800
WeapAssaultRifleAnchNV=420 ; 3000
MODAssaultRifleExtendedMag=280 ; 3200
MODAssaultRifleHeavyBarrel=265 ; 2000
; Infiltrator
; Price NV: 400
; Price Default: 500
DLC01WeapInfiltratorNV=650 ; 3800
DLC01WeapInfiltratorUniqueNV=850 ; 4500
DLC01WeapInfiltratorUniqueLaserNV=850 ; 4500
MODInfiltratorLaserSight=300 ; 1500
MODInfiltratorStock=200 ; 1500
; Combat Shotguns
; Price NV: 
; Price Default: 550
WeapNVCombatShotgun=440 ; 540
WeapNVTerribleCombatShotgun=340 ; 250
WeapNVAnchCombatShotgun=460 ; 700
ModWCSStock=150 ; 500
ModNVCSSilencer=250 ; 750
; Sniper Rifles
; Price NV: 4100
; Price Default: 300
WeapCompactSniperRifle=410 ; 4100
WeapClassicSniperRifle=380 ; 3000
WeapRangerSniperRifle=520 ; 4100
WeapReservistSniperRifle=500 ; 4100
WeapVictorySniperRifle=550 ; 4100
WeapAnchorageSniperRifle=420 ; 4100
ModNVDKSExtMags=260 ; 750
ModNVDKSBashlOt=300 ; 750
; Chinese Assault Rifles
; Price NV: 400
; Price Default: 525
WeapNVChineseRifle=640 ; 540
WeapNVChineseRifleXuanlong=700 ; 540
WeapNVChineseRifleGorilla=700 ; 540
WeapNVChineseRifleCommunist=700 ; 540
WeapNVChineseRifleAlloyedSteel=650 ; 540
WeapNVChineseRifleJunker=450 ; 540
MODNVCARFuIIStock=200 ; 1500
MODNVCARBody=250 ; 1800
MODNVCARSB=140 ; 800
; .32 Pistols
; Price NV: 110
; Price Default: 100
WeapNV32CaliberPistol=65 ; 110
WeapNV32CaliberPistolLawdog=80 ; 110
WeapNV32CaliberPistolWildBills=80 ; 110 
; Misc Weapon Mods
; Price NV: 650
; Price Default: 65
ModMVHoloSightGreen=50 ; 65
